### PR TITLE
Add run results for Nitrokey FIDO2 v2.3.0

### PR DESCRIPTION
**Pull request by szszszsz**
Hi!

Here is a result contribution for the Nitrokey FIDO2 v2.3.0.

cc @Nitrokey @jans23

### CODE REVIEW

**Comment by szszszsz** [comment]
@googlebot I signed it!

**Comment by kaczmarczyck** [comment]
Thanks for the contribution! For the CLA, please check if the email that is set in your commit matches the one you used for signing. (You probably did, just double checking.)

Concerning the result file, I see that you fail a test where we check if `GetAssertion` actually requires user presence. Chances are you noticed the warning message too late and pressed the button accidentally? Happened to other contributors, and it's on my TODO to make it more explicit. Just in case, I'll open an issue for tracking that.

**Comment by szszszsz** [comment]
> Chances are you noticed the warning message too late and pressed the button accidentally? 

Quite possibly, if it was asked right after usual confirmation requests. Perhaps adding simple warning and "Press ENTER" confirmation before timeout tests like this one would do.

In case this was tested right after the device insertion, the request was confirmed automatically by the Nitrokey FIDO2 (one single request received during the first 2 seconds). If so, then sending usual FIDO2 request before the actual timeout test would fix that.

Thank you - will check the CLA once again.

**Comment by kaczmarczyck** [comment]
Out of curiosity for that product decision: What's the benefit of having this "free" transaction after replug? Is there a specific use case for that?

**Comment by szszszsz** [comment]
This behavior is modeled after a "single use" button-less security devices, which were responding to a single request and then requiring reinsertion for the further one. Primary advantage is easier use in case the device is not always plugged in, skipping the button touch altogether.

**Comment by kaczmarczyck** [comment]
Closing this PR due to CLA problems. I copied your file to #109!

**Pull request closed without merging**
